export enum ActionType {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGOUT = "USER_LOGOUT",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL = "USER_LOGIN_FAIL",

  GET_ALL_POSTS = "GET_ALL_POSTS",
  GET_A_POST = "GET_A_POST",
  CREATE_POST = "CREATE_POST",
  UPDATE_POST = "UPDATE_POST",
  DELETE_POST = "DELETE_POST",
}
