export enum ActionType {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGOUT = "USER_LOGOUT",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL = "USER_LOGIN_FAIL",
}
